config/routes.rb
ClojurePopularity::Application.routes.draw do |map|
  root :to => "stack_overflow_questions#index"
  
  resources :git_hub_ranks, :only => [:index]
  resources :stack_overflow_questions, :only => [:index]
  resources :languages do
    member do
      get :git_hub_ranks
      get :stack_overflow_questions
    end
  end
end

app/models/git_hub_rank.rb
class GitHubRank < ActiveRecord::Base
  belongs_to :language
  
  default_scope :order => "date ASC"
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_many :git_hub_ranks
  has_many :stack_overflow_questions
  
  def self.interesting
    # all
    [Language.find_by_name("Clojure"), Language.find_by_name("Erlang"), Language.find_by_name("Haskell"), Language.find_by_name("Scala")]
  end
  
end

app/models/stack_overflow_question.rb
class StackOverflowQuestion < ActiveRecord::Base
  belongs_to :language
  
  default_scope :order => "date ASC"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :load_languages
  
  def load_languages
    @languages = Language.all
  end
end

app/controllers/git_hub_ranks_controller.rb
class GitHubRanksController < ApplicationController
  def index
    @selected_tab = "git_hub_ranks"
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController

  def stack_overflow_questions
    respond_to do |format|
      format.js do 
        language = Language.find_by_id(params[:id])
        render :nothing => true && return unless language
        data = {:label => language.name, :data => language.stack_overflow_questions.map{ |s| [s.date.to_time.to_i * 1000, s.number_of_questions]}}
        render :json => data
      end
    end
  end
  
  def git_hub_ranks
    respond_to do |format|
      format.js do 
        language = Language.find_by_id(params[:id])
        render :nothing => true && return unless language
        data = {:label => language.name, :data => language.git_hub_ranks.map{ |s| [s.date.to_time.to_i * 1000, s.rank]}}
        render :json => data
      end
    end
  end
end

app/controllers/stack_overflow_questions_controller.rb
class StackOverflowQuestionsController < ApplicationController
  def index
    @selected_tab = "stack_overflow_questions"
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/git_hub_ranks_helper.rb
module GitHubRanksHelper
end

app/views/git_hub_ranks/index.html.erb
<script type="text/javascript" charset="utf-8">
  var myData = [];

  $(document).ready(function () {
    var languages = {
      <% @languages.each do |language| -%>
        "<%= language.name %>": {
          name: "<%= language.name %>",
          id: "<%= language.id %>"
        },
      <% end -%>
    };
  
    addLanguageCheckboxes(languages);
    selectDefaultLanguages();
    plotWithData();
  });

  function addDataAndReplot() {
    var languageId = $(this).attr("name");
    var languageName = $(this).attr("id");
  
    if (removeExistingLanguage(languageName) == true) {
      $(this).parents("span").removeClass("selected");
      plotWithData();
    } else {
      $(this).parents("span").addClass("selected");
      $.getJSON('languages/' + languageId + '/git_hub_ranks', function(data) {
        myData.push(data);
        plotWithData();
      });
    }
  }

  function removeExistingLanguage(languageName) {
    deleted = false;
    $.each(myData, function(index, language) {
      if (language.label == languageName) {
        myData.splice(index, 1);
        deleted = true;
      }
    });
    return deleted;
  }

  function plotWithData() {
    if (myData.length > 0) {
      $.plot($("#placeholder"), myData, {
        yaxis: { 
          min: 0,
          invert: true
        },
        xaxis: { 
          // tickDecimals: 0, 
          mode: "time", 
          timeformat: "%m/%d/%y",
        },
        series: {
          points: { show: true, fill: true },
          lines: { show: true }
        }
      });
    } else {
      // Do something creative with the blank state
    }
  }
</script>

<div id="placeholder" style="width: 800px; height: 400px; position: relative; ">
  
</div>
<%= render :partial => 'shared/languages' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Language Popularity</title>
  <link rel="stylesheet" href="stylesheets/reset.css" type="text/css" />
  <link rel="stylesheet" href="stylesheets/screen.css" type="text/css" />
  <%= javascript_include_tag "jquery-1.4.2.min", "jquery.flot", "application" %>
</head>

<body id="index" class="home">
  <header class="body">
    <h1>Language Popularity, </h1>
    <span class="heading">as judged by</span>
    <span class="absolute">
      <ul class="heading" id="source-picker">
        <%- if @selected_tab == 'stack_overflow_questions' -%>
          <li>
            <a href="<%= stack_overflow_questions_path %>">
              StackOverflow
              <span># of Questions</span>
            </a>
          </li>
          <li>
            <a href="<%= git_hub_ranks_path %>">
              GitHub
              <span>Most Popular Language</span>
            </a>
          </li>
        <%- else -%>
          <li>
            <a href="<%= git_hub_ranks_path %>">
              GitHub
              <span>Most Popular Language</span>
            </a>
          </li>
          <li>
            <a href="<%= stack_overflow_questions_path %>">
              StackOverflow
              <span># of Questions</span>
            </a>
          </li>
        <%- end -%>
      </ul>
    </span>
  </header>
  
  <section class="body">
    <%= yield %>
  </section>
  
  <footer class="body">
    <p>Language Popularity is all about blah blah blah.</p>
  </footer>
</body>
</html>

app/views/shared/_languages.html.erb
<h2 class="choose_language">Choose languages to compare:</h2>
<ul id="choices">
  
</ul>

app/views/stack_overflow_questions/index.html.erb
<script type="text/javascript" charset="utf-8">
  var myData = [];

  $(document).ready(function () {
    var languages = {
      <% @languages.each do |language| -%>
        "<%= language.name %>": {
          name: "<%= language.name %>",
          id: "<%= language.id %>"
        },
      <% end -%>
    };
    
    addLanguageCheckboxes(languages);
    selectDefaultLanguages();
    plotWithData();
  });
  
  function addDataAndReplot() {
    var languageId = $(this).attr("name");
    var languageName = $(this).attr("id");
    
    if (removeExistingLanguage(languageName) == true) {
      $(this).parents("span").removeClass("selected");
      plotWithData();
    } else {
      $(this).parents("span").addClass("selected");
      $.getJSON('languages/' + languageId + '/stack_overflow_questions', function(data) {
        myData.push(data);
        plotWithData();
      });
    }
  }
  
  function removeExistingLanguage(languageName) {
    deleted = false;
    $.each(myData, function(index, language) {
      if (language.label == languageName) {
        myData.splice(index, 1);
        deleted = true;
      }
    });
    return deleted;
  }
  
  function plotWithData() {
    if (myData.length > 0) {
      $.plot($("#placeholder"), myData, {
        yaxis: { min: 0 },
        xaxis: { 
          // tickDecimals: 0, 
          mode: "time", 
          timeformat: "%m/%d/%y"
        },
        series: {
          points: { show: true, fill: true },
          lines: { show: true }
        }
      });
    } else {
      // Do something creative with the blank state
    }
  }

</script>

<div id="placeholder" style="width: 800px; height: 400px; position: relative; ">

</div>
<%= render :partial => 'shared/languages' %>